--- 
title: "Series de Tiempo"
author: "Jefferson Sanchez"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  Este es un reporte que consolida el trabajo realizado durante el desarrollo de la asignatura Análisis de Series de Tiempo de la Maestría en Ciencia de Datos.
  set in the _output.yml file.
  The HTML output format for this example is bookdown::gitbook,
link-citations: yes
github-repo: "rstudio/bookdown-demo"
---

# Tema de Interés

Uno de los primeros compromisos del curso consistió en elegir un tema de interés. En mi caso, elegí analizar los casos de dengue grave que se han presentado en la ciudad de Cali en el período 2015-2022, según los registros oficiales suministrados por la Secretaría de Salud Pública Municipal. La motivación principal de esta selección es que permitiría integrar los aprendizajes de este curso en los análisis que estoy realizando, junto a mis compañeros, en el marco del trabajo de grado de la Maestía en Ciencia de Datos. 

Según los hallazgos preliminares que hemos realizado, los casos de dengue grave en Cali podrían ser explicados y quizá predichos, a través de un conjunto de variables de interés que pueden obtenerse de fuentes informales. En general, este problema es relevante porque le permitiría a los responsables del sistema de salud municipal asegurar la asignación oportuna de recursos para atender de forma oportuna y eficaz los brotes de dengue grave en la ciudad.

Desde la perspectiva técnica, el conjunto de datos de trabajo que hemos construido, el cual incluye variables meteorológicas, consta de información estructurada en el tiempo, y habilitaría la experimentación con todos los referentes técnicos y herramientas que se nos suministre en el desarrollo de la asignatura Análisis de Series de Tiempo. El efecto de sinergia es evidente, especialmente al considerar que hemos realizado un ejercicio de entendimiento del problema y exploración de dinámicas alrededor del mismo durante los últimos dos semestres.


